name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sunua/go_server-example
        registry: docker.io
        username: "sunua"
        password: "0938536997"

